//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        // Impresora usada para los tiquetes de caja. Vacio = impresora predeterminada del sistema.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImpresoraTiquete
        {
            get { return ((string)(this["ImpresoraTiquete"])); }
            set { this["ImpresoraTiquete"] = value; }
        }

        // Ancho de papel (mm) a forzar en el tiquete. 0 = usar el tamano configurado en la impresora.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AnchoPapelTiqueteMM
        {
            get { return ((int)(this["AnchoPapelTiqueteMM"])); }
            set { this["AnchoPapelTiqueteMM"] = value; }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MostrarDialogoImpresionTiquete
        {
            get { return ((bool)(this["MostrarDialogoImpresionTiquete"])); }
            set { this["MostrarDialogoImpresionTiquete"] = value; }
        }
    }
}
